from __future__ import annotations

from typing import Any

from nethub_runtime.core_brain.brain.api.dto.chat_request import ChatRequest


class WorkflowBuilderService:
    def build(
        self,
        *,
        req: ChatRequest,
        task_id: str,
        intent: dict[str, Any],
        route: dict[str, Any],
        context_bundle: dict[str, Any],
    ) -> dict[str, Any]:
        return {
            "workflow_id": f"wf_{task_id}",
            "workflow_type": "business_execution",
            "source_intent_id": str(intent.get("intent_id") or f"intent_{task_id}"),
            "name": f"{intent.get('name', 'general_chat')}_workflow",
            "status": "draft",
            "version": "1.0.0",
            "goal": str(intent.get("description") or "Fulfill user intent."),
            "steps": [
                {
                    "task_id": f"{task_id}_001",
                    "step_index": 1,
                    "name": "load_context",
                    "task_type": "custom_task",
                    "objective": "Load and normalize execution context layers.",
                    "assigned_agent_type": "context_agent",
                    "assigned_agent_id": None,
                    "required_tools": [],
                    "input_schema": "context_load_input",
                    "output_schema": "context_load_output",
                    "depends_on": [],
                    "retry_policy": {"max_retries": 1, "fallback_allowed": False},
                    "validation_rule": {"type": "step_output_validation", "required_fields": ["context_bundle"]},
                    "status": "pending",
                },
                {
                    "task_id": f"{task_id}_002",
                    "step_index": 2,
                    "name": "analyze_intent",
                    "task_type": "intent_analysis",
                    "objective": "Produce a normalized intent contract from user input.",
                    "assigned_agent_type": "intent_agent",
                    "assigned_agent_id": None,
                    "required_tools": [],
                    "input_schema": "intent_parse_input",
                    "output_schema": "intent_parse_output",
                    "depends_on": [f"{task_id}_001"],
                    "retry_policy": {"max_retries": 1, "fallback_allowed": True},
                    "validation_rule": {
                        "type": "schema_validation",
                        "schema_name": "intent.schema.json",
                        "required_fields": ["intent_id", "name", "intent_type"],
                    },
                    "status": "pending",
                },
                {
                    "task_id": f"{task_id}_003",
                    "step_index": 3,
                    "name": "select_route",
                    "task_type": "route_selection",
                    "objective": "Select local-first model route with fallback policy.",
                    "assigned_agent_type": "router_agent",
                    "assigned_agent_id": None,
                    "required_tools": [],
                    "input_schema": "route_select_input",
                    "output_schema": "route_select_output",
                    "depends_on": [f"{task_id}_002"],
                    "retry_policy": {"max_retries": 1, "fallback_allowed": True},
                    "validation_rule": {"type": "step_output_validation", "required_fields": ["model"]},
                    "status": "pending",
                },
                {
                    "task_id": f"{task_id}_004",
                    "step_index": 4,
                    "name": "execute_response",
                    "task_type": "custom_task",
                    "objective": "Execute response generation for the current request.",
                    "assigned_agent_type": "chat_agent",
                    "assigned_agent_id": None,
                    "required_tools": [],
                    "input_schema": "response_generate_input",
                    "output_schema": "response_generate_output",
                    "depends_on": [f"{task_id}_003"],
                    "retry_policy": {"max_retries": 1, "fallback_allowed": True},
                    "validation_rule": {"type": "step_output_validation", "required_fields": ["answer_text"]},
                    "status": "pending",
                },
                {
                    "task_id": f"{task_id}_005",
                    "step_index": 5,
                    "name": "validate_intent_fulfillment",
                    "task_type": "validation",
                    "objective": "Validate final output against expected intent outcomes.",
                    "assigned_agent_type": "validation_agent",
                    "assigned_agent_id": None,
                    "required_tools": [],
                    "input_schema": "intent_validation_input",
                    "output_schema": "intent_validation_output",
                    "depends_on": [f"{task_id}_004"],
                    "retry_policy": {"max_retries": 0, "fallback_allowed": False},
                    "validation_rule": {
                        "type": "intent_fulfillment_validation",
                        "required_outcomes": list(intent.get("expected_outcome") or ["general_chat_completed"]),
                    },
                    "status": "pending",
                },
            ],
            "final_validation_rule": {
                "type": "intent_fulfillment_validation",
                "required_outcomes": list(intent.get("expected_outcome") or ["general_chat_completed"]),
            },
            "metadata": {
                "route_policy": {
                    "allow_external": req.allow_external,
                    "selected_model": route.get("model"),
                },
                "context_layers": {
                    "system": bool(context_bundle.get("system_context")),
                    "session_items": len(context_bundle.get("session_context") or []),
                    "task_present": bool(context_bundle.get("task_context")),
                    "long_term_items": len(context_bundle.get("long_term_context") or []),
                },
            },
        }
